// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SearchTable: typeof import('./src/components/SearchTable.vue')['default']
  }
}

export {}
